import type { Metadata } from 'next';
// import { Inter as FontSans } from 'next/font/google';
import { GeistSans } from 'geist/font/sans';
import '@/styles/globals.css';

import { cn } from '@/lib/utils';
import { ThemeProvider } from 'next-themes';
import Header from '@/components/shared/header';

// const fontSans = GeistSans({
//   subsets: ['latin'],
//   variable: '--font-sans',
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          GeistSans.variable
        )}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
