create type "public"."product_types" as enum ('no_variant', 'with_variant');

alter table "public"."cart_products" drop constraint "cart_products_cart_id_fkey";

alter table "public"."cart_products" drop constraint "cart_products_product_id_fkey";

alter table "public"."carts" drop constraint "carts_profile_id_fkey";

alter table "public"."orders" drop constraint "orders_cart_id_fkey";

alter table "public"."product_prices" drop constraint "product_prices_product_id_fkey";

alter table "public"."products" drop constraint "products_store_id_fkey";

alter table "public"."store_profiles" drop constraint "store_profiles_profile_id_fkey";

alter table "public"."store_profiles" drop constraint "store_profiles_role_id_fkey";

alter table "public"."store_profiles" drop constraint "store_profiles_store_id_fkey";

create table "public"."product_sizes" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "instance_id" bigint generated by default as identity not null,
    "price" numeric not null default '0'::numeric,
    "product_variant_id" uuid,
    "product_size_id" uuid
);


alter table "public"."product_sizes" enable row level security;

create table "public"."product_variants" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "instance_id" bigint generated by default as identity not null,
    "product_id" uuid not null,
    "name" character varying not null,
    "quantity" bigint not null default '0'::bigint
);


alter table "public"."product_variants" enable row level security;

create table "public"."store_product_categories" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "instance_id" integer generated by default as identity not null,
    "name" character varying not null,
    "store_id" uuid not null
);


alter table "public"."store_product_categories" enable row level security;

create table "public"."store_types" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "instance_id" bigint generated by default as identity not null,
    "name" character varying not null
);


alter table "public"."store_types" enable row level security;

alter table "public"."product_prices" drop column "amount";

alter table "public"."product_prices" add column "price" numeric;

alter table "public"."products" drop column "size";

alter table "public"."products" drop column "variant";

alter table "public"."products" add column "default_price" numeric not null default '0'::numeric;

alter table "public"."products" add column "description" character varying;

alter table "public"."products" add column "store_product_category_id" uuid;

alter table "public"."products" add column "total_sold" bigint not null default '0'::bigint;

alter table "public"."products" add column "type" product_types not null default 'no_variant'::product_types;

alter table "public"."products" alter column "quantity" drop default;

alter table "public"."products" alter column "quantity" set data type integer using "quantity"::integer;

alter table "public"."products" alter column "store_id" set not null;

alter table "public"."roles" alter column "role" set not null;

alter table "public"."store_profiles" alter column "role_id" set not null;

alter table "public"."store_profiles" alter column "store_id" set not null;

alter table "public"."stores" add column "store_types_id" uuid;

CREATE UNIQUE INDEX product_sizes_instance_id_key ON public.product_sizes USING btree (instance_id);

CREATE UNIQUE INDEX product_sizes_pkey ON public.product_sizes USING btree (id);

CREATE UNIQUE INDEX product_variants_instance_id_key ON public.product_variants USING btree (instance_id);

CREATE UNIQUE INDEX product_variants_pkey ON public.product_variants USING btree (id);

CREATE UNIQUE INDEX store_product_categories_instance_id_key ON public.store_product_categories USING btree (instance_id);

CREATE UNIQUE INDEX store_product_categories_pkey ON public.store_product_categories USING btree (id);

CREATE UNIQUE INDEX store_types_instance_id_key ON public.store_types USING btree (instance_id);

CREATE UNIQUE INDEX store_types_pkey ON public.store_types USING btree (id);

alter table "public"."product_sizes" add constraint "product_sizes_pkey" PRIMARY KEY using index "product_sizes_pkey";

alter table "public"."product_variants" add constraint "product_variants_pkey" PRIMARY KEY using index "product_variants_pkey";

alter table "public"."store_product_categories" add constraint "store_product_categories_pkey" PRIMARY KEY using index "store_product_categories_pkey";

alter table "public"."store_types" add constraint "store_types_pkey" PRIMARY KEY using index "store_types_pkey";

alter table "public"."product_sizes" add constraint "product_sizes_instance_id_key" UNIQUE using index "product_sizes_instance_id_key";

alter table "public"."product_sizes" add constraint "product_sizes_product_size_id_fkey" FOREIGN KEY (product_size_id) REFERENCES product_sizes(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."product_sizes" validate constraint "product_sizes_product_size_id_fkey";

alter table "public"."product_sizes" add constraint "product_sizes_product_variant_id_fkey" FOREIGN KEY (product_variant_id) REFERENCES product_variants(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."product_sizes" validate constraint "product_sizes_product_variant_id_fkey";

alter table "public"."product_variants" add constraint "product_variants_instance_id_key" UNIQUE using index "product_variants_instance_id_key";

alter table "public"."product_variants" add constraint "product_variants_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."product_variants" validate constraint "product_variants_product_id_fkey";

alter table "public"."products" add constraint "products_store_product_category_id_fkey" FOREIGN KEY (store_product_category_id) REFERENCES store_product_categories(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."products" validate constraint "products_store_product_category_id_fkey";

alter table "public"."store_product_categories" add constraint "store_product_categories_instance_id_key" UNIQUE using index "store_product_categories_instance_id_key";

alter table "public"."store_product_categories" add constraint "store_product_categories_store_id_fkey" FOREIGN KEY (store_id) REFERENCES stores(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."store_product_categories" validate constraint "store_product_categories_store_id_fkey";

alter table "public"."store_types" add constraint "store_types_instance_id_key" UNIQUE using index "store_types_instance_id_key";

alter table "public"."stores" add constraint "stores_store_types_id_fkey" FOREIGN KEY (store_types_id) REFERENCES store_types(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."stores" validate constraint "stores_store_types_id_fkey";

alter table "public"."cart_products" add constraint "cart_products_cart_id_fkey" FOREIGN KEY (cart_id) REFERENCES carts(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."cart_products" validate constraint "cart_products_cart_id_fkey";

alter table "public"."cart_products" add constraint "cart_products_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."cart_products" validate constraint "cart_products_product_id_fkey";

alter table "public"."carts" add constraint "carts_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."carts" validate constraint "carts_profile_id_fkey";

alter table "public"."orders" add constraint "orders_cart_id_fkey" FOREIGN KEY (cart_id) REFERENCES carts(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."orders" validate constraint "orders_cart_id_fkey";

alter table "public"."product_prices" add constraint "product_prices_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."product_prices" validate constraint "product_prices_product_id_fkey";

alter table "public"."products" add constraint "products_store_id_fkey" FOREIGN KEY (store_id) REFERENCES stores(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."products" validate constraint "products_store_id_fkey";

alter table "public"."store_profiles" add constraint "store_profiles_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."store_profiles" validate constraint "store_profiles_profile_id_fkey";

alter table "public"."store_profiles" add constraint "store_profiles_role_id_fkey" FOREIGN KEY (role_id) REFERENCES roles(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."store_profiles" validate constraint "store_profiles_role_id_fkey";

alter table "public"."store_profiles" add constraint "store_profiles_store_id_fkey" FOREIGN KEY (store_id) REFERENCES stores(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."store_profiles" validate constraint "store_profiles_store_id_fkey";

grant delete on table "public"."product_sizes" to "anon";

grant insert on table "public"."product_sizes" to "anon";

grant references on table "public"."product_sizes" to "anon";

grant select on table "public"."product_sizes" to "anon";

grant trigger on table "public"."product_sizes" to "anon";

grant truncate on table "public"."product_sizes" to "anon";

grant update on table "public"."product_sizes" to "anon";

grant delete on table "public"."product_sizes" to "authenticated";

grant insert on table "public"."product_sizes" to "authenticated";

grant references on table "public"."product_sizes" to "authenticated";

grant select on table "public"."product_sizes" to "authenticated";

grant trigger on table "public"."product_sizes" to "authenticated";

grant truncate on table "public"."product_sizes" to "authenticated";

grant update on table "public"."product_sizes" to "authenticated";

grant delete on table "public"."product_sizes" to "service_role";

grant insert on table "public"."product_sizes" to "service_role";

grant references on table "public"."product_sizes" to "service_role";

grant select on table "public"."product_sizes" to "service_role";

grant trigger on table "public"."product_sizes" to "service_role";

grant truncate on table "public"."product_sizes" to "service_role";

grant update on table "public"."product_sizes" to "service_role";

grant delete on table "public"."product_variants" to "anon";

grant insert on table "public"."product_variants" to "anon";

grant references on table "public"."product_variants" to "anon";

grant select on table "public"."product_variants" to "anon";

grant trigger on table "public"."product_variants" to "anon";

grant truncate on table "public"."product_variants" to "anon";

grant update on table "public"."product_variants" to "anon";

grant delete on table "public"."product_variants" to "authenticated";

grant insert on table "public"."product_variants" to "authenticated";

grant references on table "public"."product_variants" to "authenticated";

grant select on table "public"."product_variants" to "authenticated";

grant trigger on table "public"."product_variants" to "authenticated";

grant truncate on table "public"."product_variants" to "authenticated";

grant update on table "public"."product_variants" to "authenticated";

grant delete on table "public"."product_variants" to "service_role";

grant insert on table "public"."product_variants" to "service_role";

grant references on table "public"."product_variants" to "service_role";

grant select on table "public"."product_variants" to "service_role";

grant trigger on table "public"."product_variants" to "service_role";

grant truncate on table "public"."product_variants" to "service_role";

grant update on table "public"."product_variants" to "service_role";

grant delete on table "public"."store_product_categories" to "anon";

grant insert on table "public"."store_product_categories" to "anon";

grant references on table "public"."store_product_categories" to "anon";

grant select on table "public"."store_product_categories" to "anon";

grant trigger on table "public"."store_product_categories" to "anon";

grant truncate on table "public"."store_product_categories" to "anon";

grant update on table "public"."store_product_categories" to "anon";

grant delete on table "public"."store_product_categories" to "authenticated";

grant insert on table "public"."store_product_categories" to "authenticated";

grant references on table "public"."store_product_categories" to "authenticated";

grant select on table "public"."store_product_categories" to "authenticated";

grant trigger on table "public"."store_product_categories" to "authenticated";

grant truncate on table "public"."store_product_categories" to "authenticated";

grant update on table "public"."store_product_categories" to "authenticated";

grant delete on table "public"."store_product_categories" to "service_role";

grant insert on table "public"."store_product_categories" to "service_role";

grant references on table "public"."store_product_categories" to "service_role";

grant select on table "public"."store_product_categories" to "service_role";

grant trigger on table "public"."store_product_categories" to "service_role";

grant truncate on table "public"."store_product_categories" to "service_role";

grant update on table "public"."store_product_categories" to "service_role";

grant delete on table "public"."store_types" to "anon";

grant insert on table "public"."store_types" to "anon";

grant references on table "public"."store_types" to "anon";

grant select on table "public"."store_types" to "anon";

grant trigger on table "public"."store_types" to "anon";

grant truncate on table "public"."store_types" to "anon";

grant update on table "public"."store_types" to "anon";

grant delete on table "public"."store_types" to "authenticated";

grant insert on table "public"."store_types" to "authenticated";

grant references on table "public"."store_types" to "authenticated";

grant select on table "public"."store_types" to "authenticated";

grant trigger on table "public"."store_types" to "authenticated";

grant truncate on table "public"."store_types" to "authenticated";

grant update on table "public"."store_types" to "authenticated";

grant delete on table "public"."store_types" to "service_role";

grant insert on table "public"."store_types" to "service_role";

grant references on table "public"."store_types" to "service_role";

grant select on table "public"."store_types" to "service_role";

grant trigger on table "public"."store_types" to "service_role";

grant truncate on table "public"."store_types" to "service_role";

grant update on table "public"."store_types" to "service_role";


